- name: Commit and push changes
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git remote set-url origin https://x-access-token:${GH_PAT}@github.com/InovasiMasaDepan/beritaterkini.git
    git add .
    git commit -m "Update Sitemap"
    git push origin main
