name: Update Articles JSON

on:
  push:
    paths:
      - "articles/**"
      - "images/**"
  workflow_dispatch:  # Bisa dijalankan manual juga

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Beri izin eksekusi pada script
      run: chmod +x generate_articles.sh

    - name: Jalankan generate_articles.sh
      run: ./generate_articles.sh

    - name: Commit & Push Perubahan
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add articles.json
        git commit -m "🔄 Update articles.json otomatis"
        git push
