name: Generate Articles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HTML Articles
        run: |
          mkdir -p beritaterkini
          jq -c '.[]' articles.json | while read i; do
            title=$(echo $i | jq -r '.title')
            link=$(echo $i | jq -r '.link')
            desc=$(echo $i | jq -r '.description')

            cat > beritaterkini/$link <<EOF
            <!DOCTYPE html>
            <html lang="id">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>$title</title>
                <link rel="stylesheet" href="../style.css">
            </head>
            <body>
                <header>
                    <h1>$title</h1>
                </header>
                <main>
                    <p>$desc</p>
                    <a href="../index.html">Kembali ke Beranda</a>
                </main>
            </body>
            </html>
            EOF
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add beritaterkini/
          git commit -m "Generate new articles"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/InovasiMasaDepan/beritaterkini.git main
