name: Update Articles JSON

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch utama kamu
  workflow_dispatch:  # Bisa juga dijalankan manual

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update articles.json
        run: |
          echo "[" > articles.json
          for file in berita*.html; do
            title=$(grep -oP '(?<=<title>).*?(?=</title>)' "$file")
            echo "  {\"title\": \"$title\", \"description\": \"Berita terbaru.\", \"link\": \"$file\"}," >> articles.json
          done
          sed -i '$ s/,$//' articles.json  # Hapus koma terakhir
          echo "]" >> articles.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add articles.json
          git commit -m "Update articles.json otomatis"
          git push
