      - name: Generate HTML Articles
        run: |
          mkdir -p beritaterkini
          jq -c '.[]' articles.json | while read i; do
            title=$(echo $i | jq -r '.title')
            link=$(echo $i | jq -r '.link')
            desc=$(echo $i | jq -r '.description')

            cat > beritaterkini/$link <<EOF
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title</title>
    <link rel="stylesheet" href="../style.css">
</head>
<body>
    <header>
        <h1>$title</h1>
    </header>
    <main>
        <p>$desc</p>
        <a href="../index.html">Kembali ke Beranda</a>
    </main>
</body>
</html>
EOF
          done
