- name: Generate HTML Articles
  run: |
    # Pastikan direktori beritaterkini ada
    mkdir -p beritaterkini

    # Pastikan articles.json ada dan tidak kosong
    if [ ! -s articles.json ]; then
      echo "Error: articles.json tidak ditemukan atau kosong."
      exit 1
    fi

    # Loop setiap artikel dari articles.json
    jq -c '.[]' articles.json | while read i; do
      title=$(echo $i | jq -r '.title')
      link=$(echo $i | jq -r '.link')
      desc=$(echo $i | jq -r '.description')

      # Pastikan link adalah nama file yang valid
      filename=$(echo "$link" | sed 's/[^a-zA-Z0-9._-]/_/g')

      # Buat file HTML untuk artikel
      cat > "beritaterkini/$filename" <<EOF
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title</title>
    <link rel="stylesheet" href="../style.css">
</head>
<body>
    <header>
        <h1>$title</h1>
    </header>
    <main>
        <p>$desc</p>
        <a href="../index.html">Kembali ke Beranda</a>
    </main>
</body>
</html>
EOF
    done
